version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - socks:/socks
    environment:
      SECRET_KEY: '3141b64a459478f2b3b4c836f8befbf3a2b5db9431ab426573a06309604c33d3'
      GID: 101

  nginx:
    image: nginx:alpine
    volumes:
      - socks:/socks
      - ./config:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - app


volumes:
  socks:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.233.0/24
